spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/bikecyc_db?useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root 
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=${PORT:8080}
spring.mail.host=${VITE_MAIL_HOST}
spring.mail.port=${VITE_MAIL_PORT}
spring.mail.username=${VITE_MAIL_USER}
spring.mail.password=${VITE_MAIL_PASS}

# Cấu hình TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


vnpay.tmn-code=9QU1M88Y
vnpay.hash-secret=UXIQX1BTBL4J60ANVJ7WIFRXYCKV023D
vnpay.payment-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/checkout/success

vnpay.api-url=https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

